### ISSUE TITLE
libraries/Profiler.php

### ISSUE THREAD

**Issue by m1s0** [pocketarc/codeigniter#13]
Im running on PHP  8.2.18 and getting this error.
Maybe add #[\AllowDynamicProperties] can solve this

A PHP Error was encountered
Severity: 8192

Message: Creation of dynamic property CI_Profiler::$_compile_get is deprecated

Filename: libraries/Profiler.php

Line Number: 110

Backtrace:

File: C:\Users\msejc\Documents\NetBeansProjects\Horus\index.php
Line: 315
Function: require_once

**Comment by pocketarc** [comment]
This has been resolved by #12, which is now merged and will be included in the next release.
