### ISSUE TITLE
status of fork and posibility of contribution

### ISSUE THREAD

**Issue by mckaygerhard** [pocketarc/codeigniter#2]
i already reaed your objetives about this fork but i interested in also suppor this.. 

but was is your expectations.. also do you also will provide backguard compatibilty ? based on some commits seems was not tested such behaviour like commit f5d40b74bc633415939da4c69a11af09e4df70b2 that assumes only php 8.2.0 and still is incomplete

**Comment by pocketarc** [comment]
That commit was a port over from the PR where this fork was raised. This fork is currently running on environments from 7.4 to 8.2 without any known problems, and will soon be updated to work on PHP 8.3 as well.

If you spot anything that isn't working properly, either in PHP 8.2 or other PHP versions, feel free to raise an issue, I'd be happy to have a look at that.

Edit: Note, I do not have CI up and running for this fork (yet), so automated testing isn't happening at the moment.

**Comment by mckaygerhard** [comment]
Thanks .. i will use this and try to apport to improve it! i will mantain a fork into that org and pull to this repo the contributions
