### ISSUE TITLE
Fix library email PHP 8.x compatibilty

### ISSUE THREAD

**Issue by ludobesse** [pocketarc/codeigniter#7]
Line 427: $this->charset = strtoupper((string) $this->charset);

**Comment by poodle123** [comment]
Can you share the problem? Or do you just refer to the missing check - if (isset($this->charset)) { ... } ? My understanding is that its set prior under line 151: public $charset = 'utf-8';

I am running this on PHP 8.3.4 with extensive usage of the email library and dont see any error in my logs or any issue with sending emails.

I am using the default 'mail' protocoll without any specific configuration as well as smtp through SSL for newsletters (sending >10000 within an hour) and I see no problems with sendng email. What settings do you use?

**Comment by ludobesse** [comment]
I get this error message when loading the library (autoload) 

strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated 
/XXXXXX/vendor/pocketarc/codeigniter/system/libraries/Email.php 
Line 427

**Comment by poodle123** [comment]
this might be a problem on your side. charset is defined in line 15 and not overwritten so I dont see how it could be null.

**Comment by ludobesse** [comment]
Sorry, the problem was on my part.
I had an old config file that hadn't been deleted.
